--[[
* nmdata.lua - researched respawn/cooldown numbers, keyed by ZONE + MOB.
*
* WHY THIS EXISTS
*   phtimer's auto-register has to guess an interval on a mob's first kill,
*   and a flat guess is wrong nearly everywhere: Castle Oztroja placeholders
*   are 16 minutes, South Gustaberg's Rock Lizards are 5m30s. Same guess for
*   both is useless. This table lets the first kill use the real number.
*
* WHY IT IS BAKED IN RATHER THAN FETCHED
*   Ashita ships LuaSocket, so an addon *could* hit the wiki at runtime. It
*   should not: an HTTP call inside d3d_present blocks the frame, the Horizon
*   wiki times out for minutes at a stretch (observed repeatedly 2026-08-25),
*   and an addon making outbound calls is a rules question nobody needs. These
*   numbers were read off the wiki offline and pasted here. Re-check them if
*   Horizon rebases again.
*
* ZONE MATCHING
*   Zone comes from AshitaCore:GetMemoryManager():GetParty():GetMemberZone(0)
*   resolved through the resource manager - your own party record, NOT an
*   entity-table scan. Keys are lowercase zone names.
*
* FIELDS
*   ph   placeholder respawn, seconds - the countdown to your next lottery roll
*   cd   NM post-kill cooldown, seconds - dead time when no pop is possible
*   note provenance, so a wrong number can be traced instead of trusted
--]]

local M = {};

-- Timer tables generated from LandSandBoat source, 2026-08-26.
--
-- SOURCE: every lottery placeholder script ends with
--     xi.mob.phOnDespawn(mob, ID.mob.<NM>, <chance>, <cooldown>)
-- which is the authoritative pop chance and NM cooldown. Scraped from 4,718
-- mob scripts: 341 placeholder definitions, 100 zones, 317 NMs.
--
-- Hand-copied wiki values were wrong twice before this (Quu Domi's cooldown is
-- 3600, not the 3000 assumed from Mee Deggi), and the wiki does not publish
-- most of them at all.
--
-- FIELDS
--   cd   NM post-kill cooldown, seconds  (phOnDespawn arg 4)
--   pop  lottery chance per placeholder death, percent  (arg 3)
--   nm   which NM this placeholder rolls for
--   ph   placeholder respawn seconds - NOT from source. phOnDespawn does not
--        carry it and mob_groups has no rows for these zones on base. Only
--        the measured Castle Oztroja / South Gustaberg values are filled in.
M.zones = {
    ['alzadaal undersea ruins'] = {
        ['cookieduster lipiroon'] = { cd = 3600, pop = 15 },
        ['qiqirn goldsmith'] = { pop = 15, nm = 'Cookieduster Lipiroon' },
    },
    ['arrapago reef'] = {
        ['bloody bones'] = { cd = 75600, pop = 5 },
        ['draugar servant'] = { pop = 5, nm = 'Bloody Bones' },
    },
    ['attohwa chasm'] = {
        ['ambusher antlion'] = { cd = 3600, pop = 15 },
        ['trench antlion'] = { pop = 15, nm = 'Ambusher Antlion' },
    },
    ['aydeewa subterrane'] = {
        ['bluestreak gyugyuroon'] = { cd = 7200, pop = 10 },
        ['qiqirn archaeologist'] = { pop = 10, nm = 'Bluestreak Gyugyuroon' },
    },
    ['batallia downs'] = {
        ['ba'] = { pop = 20, nm = 'Tottering Toby' },
        ['evil weapon'] = { pop = 15, nm = 'Prankster Maverix' },
        ['prankster maverix'] = { cd = 3600, pop = 15 },
        ['stalking sapling'] = { pop = 20, nm = 'Tottering Toby' },
        ['tottering toby'] = { cd = 3600, pop = 20 },
    },
    ['batallia downs [s]'] = {
        ['ba'] = { pop = 10, nm = 'Habergoass' },
        ['burlibix brawnback'] = { cd = 10800, pop = 10 },
        ['goblin blastmaster'] = { pop = 10, nm = 'Burlibix Brawnback' },
        ['habergoass'] = { cd = 5400, pop = 10 },
        ['la velue'] = { cd = 3600, pop = 10 },
        ['smilodon'] = { pop = 10, nm = 'La Velue' },
    },
    ['beadeaux'] = {
        ['bi gho headtaker'] = { cd = 3600, pop = 10 },
        ['brass quadav'] = { pop = 10, nm = 'Bi Gho Headtaker' },
        ['copper quadav'] = { pop = 10, nm = 'Da Dha Hundredmask' },
        ['da dha hundredmask'] = { cd = 5400, pop = 10 },
        ['emerald quadav'] = { pop = 10, nm = 'Ga Bhu Unvanquished' },
        ['ga bhu unvanquished'] = { cd = 3600, pop = 10 },
        ['ge dha evileye'] = { cd = 3600, pop = 25 },
        ['old quadav'] = { pop = 25, nm = 'Ge Dha Evileye' },
        ['zircon quadav'] = { pop = 10, nm = 'Zo Khu Blackcloud' },
        ['zo khu blackcloud'] = { cd = 3600, pop = 10 },
    },
    ['beadeaux [s]'] = {
        ['adaman quadav'] = { pop = 10, nm = 'Eatho Cruelheart' },
        ['da dha hundredmask'] = { cd = 7200, pop = 12 },
        ['eatho cruelheart'] = { cd = 7200, pop = 10 },
        ['gold quadav'] = { pop = 12, nm = 'Da Dha Hundredmask' },
    },
    ['beaucedine glacier [s]'] = {
        ['gargouille'] = { pop = 10, nm = 'Grandgoule' },
        ['grandgoule'] = { cd = 3600, pop = 10 },
    },
    ['bhaflau thickets'] = {
        ['emergent elm'] = { cd = 7200, pop = 5 },
        ['mahishasura'] = { cd = 10800, pop = 15 },
        ['marid'] = { pop = 15, nm = 'Mahishasura' },
        ['olden treant'] = { pop = 5, nm = 'Emergent Elm' },
    },
    ['bibiki bay'] = {
        ['eft'] = { pop = 10, nm = 'Intulo' },
        ['intulo'] = { cd = 3600, pop = 10 },
        ['jagil'] = { pop = 10, nm = 'Serra' },
        ['serra'] = { cd = 3600, pop = 10 },
        ['splacknuck'] = { cd = 3600, pop = 10 },
        ['tartarus eft'] = { pop = 10, nm = 'Splacknuck' },
    },
    ['bostaunieux oubliette'] = {
        ['arioch'] = { cd = 3600, pop = 10 },
        ['garm'] = { pop = 5, nm = 'Shii' },
        ['gespenst'] = { pop = 5, nm = 'Manes' },
        ['manes'] = { cd = 3600, pop = 5 },
        ['mousse'] = { pop = 10, nm = 'Sewer Syrup' },
        ['sewer syrup'] = { cd = 7200, pop = 10 },
        ['shii'] = { cd = 3600, pop = 5 },
        ['werebat'] = { pop = 10, nm = 'Arioch' },
    },
    ['buburimu peninsula'] = {
        ['buburimboo'] = { cd = 3600, pop = 10 },
        ['helldiver'] = { cd = 3600, pop = 10 },
        ['shoal pugil'] = { pop = 10, nm = 'Buburimboo' },
        ['zu'] = { pop = 10, nm = 'Helldiver' },
    },
    ['cape teriggan'] = {
        ['frostmane'] = { cd = 3600, pop = 5 },
        ['greater manticore'] = { pop = 5, nm = 'Frostmane' },
    },
    ['carpenters landing'] = {
        ['birdtrap'] = { pop = 10, nm = 'Orctrap' },
        ['orctrap'] = { cd = 3600, pop = 10 },
    },
    ['castle oztroja'] = {
        ['mee deggi the punisher'] = { cd = 3000, pop = 5 },
        ['moo ouzi the swiftblade'] = { cd = 3600, pop = 5 },
        ['quu domi the gallant'] = { cd = 3600, pop = 5 },
        ['yaa haqa the profane'] = { cd = 3600, pop = 5 },
        ['yagudo conquistador'] = { pop = 5, nm = 'Yaa Haqa The Profane' },
        ['yagudo drummer'] = { ph = 960, pop = 5, nm = 'Mee Deggi The Punisher' },
        ['yagudo herald'] = { ph = 960, pop = 5, nm = 'Quu Domi The Gallant' },
        ['yagudo interrogator'] = { ph = 960, pop = 5, nm = 'Mee Deggi The Punisher' },
        ['yagudo lutenist'] = { pop = 5, nm = 'Yaa Haqa The Profane' },
        ['yagudo oracle'] = { ph = 960, pop = 5, nm = 'Quu Domi The Gallant' },
        ['yagudo prior'] = { pop = 5, nm = 'Yaa Haqa The Profane' },
        ['yagudo theologist'] = { pop = 5, nm = 'Moo Ouzi The Swiftblade' },
        ['yagudo zealot'] = { pop = 5, nm = 'Yaa Haqa The Profane' },
    },
    ['castle oztroja [s]'] = {
        ['aa xalmo the savage'] = { cd = 7200, pop = 10 },
        ['yagudo sentinel'] = { pop = 10, nm = 'Aa Xalmo The Savage' },
    },
    ['castle zvahl baileys'] = {
        ['abyssal demon'] = { pop = 10, nm = 'Marquis Sabnock' },
        ['doom demon'] = { pop = 10, nm = 'Marquis Sabnock' },
        ['marquis sabnock'] = { cd = 7200, pop = 10 },
    },
    ['castle zvahl keep'] = {
        ['baron vapula'] = { cd = 1, pop = 10 },
        ['baronet romwe'] = { cd = 1, pop = 10 },
        ['count bifrons'] = { cd = 1, pop = 10 },
        ['demon knight'] = { pop = 10, nm = 'Count Bifrons' },
        ['demon pawn'] = { pop = 10, nm = 'Baronet Romwe' },
        ['demon warlock'] = { pop = 10, nm = 'Viscount Morax' },
        ['demon wizard'] = { pop = 10, nm = 'Baron Vapula' },
        ['viscount morax'] = { cd = 1, pop = 10 },
    },
    ['crawlers nest [s]'] = {
        ['morille mortelle'] = { cd = 18000, pop = 12 },
        ['witch hazel'] = { pop = 12, nm = 'Morille Mortelle' },
    },
    ['dangruf wadi'] = {
        ['hoarder hare'] = { pop = 20, nm = 'Teporingo' },
        ['teporingo'] = { cd = 3600, pop = 20 },
    },
    ['davoi'] = {
        ['blubbery bulge'] = { cd = 3600, pop = 20 },
        ['davoi mush'] = { pop = 20, nm = 'Blubbery Bulge' },
        ['hawkeyed dnatbat'] = { cd = 3600, pop = 10 },
        ['orcish beastrider'] = { pop = 10, nm = 'Poisonhand Gnadgad' },
        ['orcish brawler'] = { pop = 10, nm = 'Poisonhand Gnadgad' },
        ['orcish cursemaker'] = { pop = 10, nm = 'Hawkeyed Dnatbat' },
        ['orcish firebelcher'] = { pop = 10, nm = 'Poisonhand Gnadgad' },
        ['orcish impaler'] = { pop = 10, nm = 'Poisonhand Gnadgad' },
        ['orcish nightraider'] = { pop = 10, nm = 'Poisonhand Gnadgad' },
        ['poisonhand gnadgad'] = { cd = 3600, pop = 10 },
        ['tigerbane bakdak'] = { cd = 3600, pop = 10 },
        ['war lizard'] = { pop = 10, nm = 'Tigerbane Bakdak' },
    },
    ['den of rancor'] = {
        ['bifrons'] = { pop = 10, nm = 'Friar Rush' },
        ['bistre hearted malberry'] = { cd = 3600, pop = 10 },
        ['carmine tailed janberry'] = { cd = 3600, pop = 5 },
        ['celeste eyed tozberry'] = { cd = 7200, pop = 10 },
        ['doom toad'] = { pop = 5, nm = 'Ogama' },
        ['friar rush'] = { cd = 3600, pop = 10 },
        ['ogama'] = { cd = 3600, pop = 5 },
        ['tawny fingered mugberry'] = { cd = 3600, pop = 5 },
        ['tonberry beleaguerer'] = { pop = 10, nm = 'Bistre Hearted Malberry' },
        ['tonberry imprecator'] = { pop = 5, nm = 'Carmine Tailed Janberry' },
        ['tonberry slasher'] = { pop = 5, nm = 'Tawny Fingered Mugberry' },
        ['tonberry trailer'] = { pop = 10, nm = 'Celeste Eyed Tozberry' },
    },
    ['dynamis-beaucedine'] = {
        ['ascetox ratgums'] = { cd = 1200, pop = 10 },
        ['bezhe keeprazer'] = { cd = 1200, pop = 10 },
        ['bhuu wjato the firepool'] = { cd = 1200, pop = 10 },
        ['bordox kittyback'] = { cd = 1200, pop = 10 },
        ['brewnix bittypupils'] = { cd = 1200, pop = 10 },
        ['caa xaza the madpiercer'] = { cd = 1200, pop = 10 },
        ['cobraclaw buchzvotch'] = { cd = 1200, pop = 10 },
        ['deathcaller bidfbid'] = { cd = 1200, pop = 10 },
        ['debho pyrohand'] = { cd = 1200, pop = 10 },
        ['drakefeast wubmfub'] = { cd = 1200, pop = 10 },
        ['draklix scalecrust'] = { cd = 1200, pop = 10 },
        ['droprix granitepalms'] = { cd = 1200, pop = 10 },
        ['elvaanlopper grokdok'] = { cd = 1200, pop = 10 },
        ['foo peku the bloodcloak'] = { cd = 1200, pop = 10 },
        ['gafho venomtouch'] = { cd = 1200, pop = 10 },
        ['galkarider retzpratz'] = { cd = 1200, pop = 10 },
        ['gibberox pimplebeak'] = { cd = 1200, pop = 10 },
        ['gotyo magenapper'] = { cd = 1200, pop = 10 },
        ['gukhu dukesniper'] = { cd = 1200, pop = 10 },
        ['gunha wallstormer'] = { cd = 1200, pop = 10 },
        ['guu waji the preacher'] = { cd = 1200, pop = 10 },
        ['heavymail djidzbad'] = { cd = 1200, pop = 10 },
        ['hee mida the meticulous'] = { cd = 1200, pop = 10 },
        ['humegutter adzjbadj'] = { cd = 1200, pop = 10 },
        ['jeunoraider gepkzip'] = { cd = 1200, pop = 10 },
        ['jifhu infiltrator'] = { cd = 1200, pop = 10 },
        ['jikhu towercleaver'] = { cd = 1200, pop = 10 },
        ['knii hoqo the bisector'] = { cd = 1200, pop = 10 },
        ['koo saxu the everfast'] = { cd = 1200, pop = 10 },
        ['kuu xuka the nimble'] = { cd = 1200, pop = 10 },
        ['lockbuster zapdjipp'] = { cd = 1200, pop = 10 },
        ['maa zaua the wyrmkeeper'] = { cd = 1200, pop = 10 },
        ['mirhe whisperblade'] = { cd = 1200, pop = 10 },
        ['mithraslaver debhabob'] = { cd = 1200, pop = 10 },
        ['moltenox stubthumbs'] = { cd = 1200, pop = 10 },
        ['morblox chubbychin'] = { cd = 1200, pop = 10 },
        ['mugha legionkiller'] = { cd = 1200, pop = 10 },
        ['nahya floodmaker'] = { cd = 1200, pop = 10 },
        ['nee huxa the judgmental'] = { cd = 1200, pop = 10 },
        ['nubhi spiraleye'] = { cd = 1200, pop = 10 },
        ['puu timu the phantasmal'] = { cd = 1200, pop = 10 },
        ['routsix rubbertendon'] = { cd = 1200, pop = 10 },
        ['ruffbix jumbolobes'] = { cd = 1200, pop = 10 },
        ['ryy qihi the idolrobber'] = { cd = 1200, pop = 10 },
        ['shisox widebrow'] = { cd = 1200, pop = 10 },
        ['skinmask ugghfogg'] = { cd = 1200, pop = 10 },
        ['slinkix trufflesniff'] = { cd = 1200, pop = 10 },
        ['sogho adderhandler'] = { cd = 1200, pop = 10 },
        ['soo jopo the fiendking'] = { cd = 1200, pop = 10 },
        ['sozho metalbender'] = { cd = 1200, pop = 10 },
        ['spinalsucker galflmall'] = { cd = 1200, pop = 10 },
        ['swypestix tigershins'] = { cd = 1200, pop = 10 },
        ['tahyu gallanthunter'] = { cd = 1200, pop = 10 },
        ['taruroaster biggsjig'] = { cd = 1200, pop = 10 },
        ['tocktix thinlids'] = { cd = 1200, pop = 10 },
        ['ultrasonic zeknajak'] = { cd = 1200, pop = 10 },
        ['vanguard alchemist'] = { pop = 10, nm = 'Brewnix Bittypupils' },
        ['vanguard ambusher'] = { pop = 10, nm = 'Slinkix Trufflesniff' },
        ['vanguard amputator'] = { pop = 10, nm = 'Wraithdancer Gidbnod' },
        ['vanguard armorer'] = { pop = 10, nm = 'Ruffbix Jumbolobes' },
        ['vanguard assassin'] = { pop = 10, nm = 'Kuu Xuka The Nimble' },
        ['vanguard backstabber'] = { pop = 10, nm = 'Jeunoraider Gepkzip' },
        ['vanguard beasttender'] = { pop = 10, nm = 'Sogho Adderhandler' },
        ['vanguard bugler'] = { pop = 10, nm = 'Ultrasonic Zeknajak' },
        ['vanguard chanter'] = { pop = 10, nm = 'Xhoo Fuza The Sublime' },
        ['vanguard constable'] = { pop = 10, nm = 'Gafho Venomtouch' },
        ['vanguard defender'] = { pop = 10, nm = 'Mugha Legionkiller' },
        ['vanguard dollmaster'] = { pop = 10, nm = 'Deathcaller Bidfbid' },
        ['vanguard dragontamer'] = { pop = 10, nm = 'Draklix Scalecrust' },
        ['vanguard drakekeeper'] = { pop = 10, nm = 'Gotyo Magenapper' },
        ['vanguard enchanter'] = { pop = 10, nm = 'Gibberox Pimplebeak' },
        ['vanguard exemplar'] = { pop = 10, nm = 'Guu Waji The Preacher' },
        ['vanguard footsoldier'] = { pop = 10, nm = 'Humegutter Adzjbadj' },
        ['vanguard grappler'] = { pop = 10, nm = 'Cobraclaw Buchzvotch' },
        ['vanguard gutslasher'] = { pop = 10, nm = 'Elvaanlopper Grokdok' },
        ['vanguard hatamoto'] = { pop = 10, nm = 'Jikhu Towercleaver' },
        ['vanguard hawker'] = { pop = 10, nm = 'Mithraslaver Debhabob' },
        ['vanguard hitman'] = { pop = 10, nm = 'Swypestix Tigershins' },
        ['vanguard impaler'] = { pop = 10, nm = 'Drakefeast Wubmfub' },
        ['vanguard inciter'] = { pop = 10, nm = 'Nee Huxa The Judgmental' },
        ['vanguard kusa'] = { pop = 10, nm = 'Mirhe Whisperblade' },
        ['vanguard liberator'] = { pop = 10, nm = 'Ryy Qihi The Idolrobber' },
        ['vanguard maestro'] = { pop = 10, nm = 'Whistrix Toadthroat' },
        ['vanguard mason'] = { pop = 10, nm = 'Gukhu Dukesniper' },
        ['vanguard mesmerizer'] = { pop = 10, nm = 'Taruroaster Biggsjig' },
        ['vanguard militant'] = { pop = 10, nm = 'Sozho Metalbender' },
        ['vanguard minstrel'] = { pop = 10, nm = 'Nubhi Spiraleye' },
        ['vanguard neckchopper'] = { pop = 10, nm = 'Skinmask Ugghfogg' },
        ['vanguard necromancer'] = { pop = 10, nm = 'Morblox Chubbychin' },
        ['vanguard ogresoother'] = { pop = 10, nm = 'Soo Jopo The Fiendking' },
        ['vanguard oracle'] = { pop = 10, nm = 'Puu Timu The Phantasmal' },
        ['vanguard partisan'] = { pop = 10, nm = 'Maa Zaua The Wyrmkeeper' },
        ['vanguard pathfinder'] = { pop = 10, nm = 'Routsix Rubbertendon' },
        ['vanguard persecutor'] = { pop = 10, nm = 'Knii Hoqo The Bisector' },
        ['vanguard pillager'] = { pop = 10, nm = 'Lockbuster Zapdjipp' },
        ['vanguard pitfighter'] = { pop = 10, nm = 'Droprix Granitepalms' },
        ['vanguard predator'] = { pop = 10, nm = 'Galkarider Retzpratz' },
        ['vanguard prelate'] = { pop = 10, nm = 'Bhuu Wjato The Firepool' },
        ['vanguard priest'] = { pop = 10, nm = 'Koo Saxu The Everfast' },
        ['vanguard protector'] = { pop = 10, nm = 'Nahya Floodmaker' },
        ['vanguard purloiner'] = { pop = 10, nm = 'Jifhu Infiltrator' },
        ['vanguard ronin'] = { pop = 10, nm = 'Shisox Widebrow' },
        ['vanguard salvager'] = { pop = 10, nm = 'Hee Mida The Meticulous' },
        ['vanguard sentinel'] = { pop = 10, nm = 'Xaa Chau The Roctalon' },
        ['vanguard shaman'] = { pop = 10, nm = 'Ascetox Ratgums' },
        ['vanguard skirmisher'] = { pop = 10, nm = 'Foo Peku The Bloodcloak' },
        ['vanguard smithy'] = { pop = 10, nm = 'Moltenox Stubthumbs' },
        ['vanguard thaumaturge'] = { pop = 10, nm = 'Debho Pyrohand' },
        ['vanguard tinkerer'] = { pop = 10, nm = 'Tocktix Thinlids' },
        ['vanguard trooper'] = { pop = 10, nm = 'Heavymail Djidzbad' },
        ['vanguard undertaker'] = { pop = 10, nm = 'Bezhe Keeprazer' },
        ['vanguard vexer'] = { pop = 10, nm = 'Spinalsucker Galflmall' },
        ['vanguard vigilante'] = { pop = 10, nm = 'Tahyu Gallanthunter' },
        ['vanguard vindicator'] = { pop = 10, nm = 'Gunha Wallstormer' },
        ['vanguard visionary'] = { pop = 10, nm = 'Caa Xaza The Madpiercer' },
        ['vanguard welldigger'] = { pop = 10, nm = 'Bordox Kittyback' },
        ['whistrix toadthroat'] = { cd = 1200, pop = 10 },
        ['wraithdancer gidbnod'] = { cd = 1200, pop = 10 },
        ['xaa chau the roctalon'] = { cd = 1200, pop = 10 },
        ['xhoo fuza the sublime'] = { cd = 1200, pop = 10 },
    },
    ['dynamis-buburimu'] = {
        ['baa dava the bibliophage'] = { cd = 1200, pop = 10 },
        ['doo peku the fleetfoot'] = { cd = 1200, pop = 10 },
        ['elvaansticker bxafraff ph'] = { cd = 1200, pop = 10 },
        ['flamecaller zoeqdoq ph'] = { cd = 1200, pop = 10 },
        ['gibhe fleshfeaster'] = { cd = 1200, pop = 10 },
        ['gosspix blabberlips'] = { cd = 1200, pop = 10 },
        ['hamfist gukhbuk'] = { cd = 1200, pop = 10 },
        ['koo rahi the levinblade'] = { cd = 1200, pop = 10 },
        ['lyncean juwgneg'] = { cd = 1200, pop = 10 },
        ['qupho bloodspiller'] = { cd = 1200, pop = 10 },
        ['ree nata the melomanic'] = { cd = 1200, pop = 10 },
        ['shamblix rottenheart'] = { cd = 1200, pop = 10 },
        ['tezha ironclad'] = { cd = 1200, pop = 10 },
        ['vanguard assassin'] = { pop = 10, nm = 'Doo Peku The Fleetfoot' },
        ['vanguard chanter'] = { pop = 10, nm = 'Ree Nata The Melomanic' },
        ['vanguard constable'] = { pop = 10, nm = 'Gibhe Fleshfeaster' },
        ['vanguard defender'] = { pop = 10, nm = 'Tezha Ironclad' },
        ['vanguard enchanter'] = { pop = 10, nm = 'Gosspix Blabberlips' },
        ['vanguard grappler'] = { pop = 10, nm = 'Hamfist Gukhbuk' },
        ['vanguard impaler'] = { pop = 10, nm = 'Flamecaller Zoeqdoq Ph' },
        ['vanguard mesmerizer'] = { pop = 10, nm = 'Elvaansticker Bxafraff Ph' },
        ['vanguard oracle'] = { pop = 10, nm = 'Baa Dava The Bibliophage' },
        ['vanguard pathfinder'] = { pop = 10, nm = 'Woodnix Shrillwhistle' },
        ['vanguard persecutor'] = { pop = 10, nm = 'Koo Rahi The Levinblade' },
        ['vanguard predator'] = { pop = 10, nm = 'Lyncean Juwgneg' },
        ['vanguard purloiner'] = { pop = 10, nm = 'Varhu Bodysnatcher' },
        ['vanguard tinkerer'] = { pop = 10, nm = 'Shamblix Rottenheart' },
        ['vanguard vindicator'] = { pop = 10, nm = 'Qupho Bloodspiller' },
        ['varhu bodysnatcher'] = { cd = 1200, pop = 10 },
        ['woodnix shrillwhistle'] = { cd = 1200, pop = 10 },
    },
    ['dynamis-jeuno'] = {
        ['anvilix sootwrists'] = { cd = 1200, pop = 10 },
        ['blazox boneybod'] = { cd = 1200, pop = 10 },
        ['bootrix jaggedelbow'] = { cd = 1200, pop = 10 },
        ['distilix stickytoes'] = { cd = 1200, pop = 10 },
        ['eremix snottynostril'] = { cd = 1200, pop = 10 },
        ['gabblox magpietongue'] = { cd = 1200, pop = 10 },
        ['hermitrix toothrot'] = { cd = 1200, pop = 10 },
        ['mobpix mucousmouth'] = { cd = 1200, pop = 10 },
        ['mortilox wartpaws'] = { cd = 1200, pop = 10 },
        ['prowlox barrelbelly'] = { cd = 1200, pop = 10 },
        ['rutrix hamgams'] = { cd = 1200, pop = 10 },
        ['slystix megapeepers'] = { cd = 1200, pop = 10 },
        ['tymexox ninefingers'] = { cd = 1200, pop = 10 },
        ['vanguard alchemist'] = { pop = 10, nm = 'Distilix Stickytoes' },
        ['vanguard ambusher'] = { pop = 10, nm = 'Prowlox Barrelbelly' },
        ['vanguard armorer'] = { pop = 10, nm = 'Gabblox Magpietongue' },
        ['vanguard dragontamer'] = { pop = 10, nm = 'Rutrix Hamgams' },
        ['vanguard enchanter'] = { pop = 10, nm = 'Hermitrix Toothrot' },
        ['vanguard hitman'] = { pop = 10, nm = 'Slystix Megapeepers' },
        ['vanguard necromancer'] = { pop = 10, nm = 'Mortilox Wartpaws' },
        ['vanguard pathfinder'] = { pop = 10, nm = 'Blazox Boneybod' },
        ['vanguard pitfighter'] = { pop = 10, nm = 'Bootrix Jaggedelbow' },
        ['vanguard shaman'] = { pop = 10, nm = 'Eremix Snottynostril' },
        ['vanguard smithy'] = { pop = 10, nm = 'Anvilix Sootwrists' },
        ['vanguard tinkerer'] = { pop = 10, nm = 'Tymexox Ninefingers' },
        ['vanguard welldigger'] = { pop = 10, nm = 'Mobpix Mucousmouth' },
    },
    ['dynamis-xarcabard'] = {
        ['count raum'] = { cd = 1200, pop = 10 },
        ['count vine'] = { cd = 1200, pop = 10 },
        ['count zaebos'] = { cd = 1200, pop = 10 },
        ['duke berith'] = { cd = 1200, pop = 10 },
        ['duke gomory'] = { cd = 1200, pop = 10 },
        ['duke scox'] = { cd = 1200, pop = 10 },
        ['kindred bard'] = { pop = 10, nm = 'Marquis Decarabia' },
        ['kindred beastmaster'] = { pop = 10, nm = 'Marquis Andras' },
        ['kindred black mage'] = { pop = 10, nm = 'Marquis Orias' },
        ['kindred dark knight'] = { pop = 10, nm = 'Duke Scox' },
        ['kindred dragoon'] = { pop = 10, nm = 'King Zagan' },
        ['kindred monk'] = { pop = 10, nm = 'Duke Gomory' },
        ['kindred ninja'] = { pop = 10, nm = 'Marquis Gamygyn' },
        ['kindred paladin'] = { pop = 10, nm = 'Marquis Sabnak' },
        ['kindred ranger'] = { pop = 10, nm = 'Marquis Cimeries' },
        ['kindred red mage'] = { pop = 10, nm = 'Duke Berith' },
        ['kindred samurai'] = { pop = 10, nm = 'Count Vine' },
        ['kindred summoner'] = { pop = 10, nm = 'Marquis Nebiros' },
        ['kindred thief'] = { pop = 10, nm = 'Count Raum' },
        ['kindred warrior'] = { pop = 10, nm = 'Count Zaebos' },
        ['kindred white mage'] = { pop = 10, nm = 'Prince Seere' },
        ['king zagan'] = { cd = 1200, pop = 10 },
        ['marquis andras'] = { cd = 1200, pop = 10 },
        ['marquis cimeries'] = { cd = 1200, pop = 10 },
        ['marquis decarabia'] = { cd = 1200, pop = 10 },
        ['marquis gamygyn'] = { cd = 1200, pop = 10 },
        ['marquis nebiros'] = { cd = 1200, pop = 10 },
        ['marquis orias'] = { cd = 1200, pop = 10 },
        ['marquis sabnak'] = { cd = 1200, pop = 10 },
        ['prince seere'] = { cd = 1200, pop = 10 },
    },
    ['east ronfaure'] = {
        ['bigmouth billy'] = { cd = 1300, pop = 7 },
        ['carrion worm'] = { pop = 7, nm = 'Bigmouth Billy' },
    },
    ['east ronfaure [s]'] = {
        ['battrap'] = { pop = 5, nm = 'Goblintrap' },
        ['goblintrap'] = { cd = 3600, pop = 5 },
        ['ladybug'] = { pop = 5, nm = 'Skogs Fru' },
        ['skogs fru'] = { cd = 3600, pop = 5 },
    },
    ['east sarutabaruta'] = {
        ['crawler'] = { pop = 10, nm = 'Spiny Spipi' },
        ['savanna rarab'] = { pop = 20, nm = 'Sharp Eared Ropipi' },
        ['sharp eared ropipi'] = { cd = 300, pop = 20 },
        ['spiny spipi'] = { cd = 2700, pop = 10 },
    },
    ['eastern altepa desert'] = {
        ['donnergugi'] = { cd = 3600, pop = 10 },
        ['dune widow'] = { cd = 3600, pop = 10 },
        ['giant spider'] = { pop = 10, nm = 'Dune Widow' },
        ['sand beetle'] = { pop = 10, nm = 'Donnergugi' },
    },
    ['feiyin'] = {
        ['colossus'] = { pop = 15, nm = 'Goliath' },
        ['goliath'] = { cd = 1, pop = 15 },
    },
    ['fort ghelsba'] = {
        ['hundredscar hajwaj'] = { cd = 3600, pop = 10 },
        ['orcish grappler'] = { pop = 10, nm = 'Hundredscar Hajwaj' },
    },
    ['fort karugo-narugo [s]'] = {
        ['demoiselle desolee'] = { cd = 3600, pop = 5 },
        ['dragonfly'] = { pop = 5, nm = 'Demoiselle Desolee' },
        ['kirtimukha'] = { cd = 3600, pop = 5 },
        ['rafflesia'] = { pop = 5, nm = 'Kirtimukha' },
        ['ratatoskr'] = { cd = 5400, pop = 10 },
        ['vorpal bunny'] = { pop = 10, nm = 'Ratatoskr' },
    },
    ['garlaige citadel'] = {
        ['explosure'] = { pop = 10, nm = 'Hazmat' },
        ['fallen mage'] = { pop = 20, nm = 'Hovering Hotpot' },
        ['fallen major'] = { pop = 20, nm = 'Hovering Hotpot' },
        ['hazmat'] = { cd = 3600, pop = 10 },
        ['hovering hotpot'] = { cd = 1800, pop = 20 },
    },
    ['ghelsba outpost'] = {
        ['orcish grunt'] = { pop = 5, nm = 'Thousandarm Deshglesh' },
        ['orcish neckchopper'] = { pop = 5, nm = 'Thousandarm Deshglesh' },
        ['orcish stonechucker'] = { pop = 5, nm = 'Thousandarm Deshglesh' },
        ['thousandarm deshglesh'] = { cd = 3600, pop = 5 },
    },
    ['giddeus'] = {
        ['hoo mjuu the torrent'] = { cd = 3600, pop = 12 },
        ['juu duzu the whirlwind'] = { cd = 3600, pop = 5 },
        ['vuu puqu the beguiler'] = { cd = 900, pop = 15 },
        ['yagudo mendicant'] = { pop = 12, nm = 'Hoo Mjuu The Torrent' },
        ['yagudo persecutor'] = { pop = 5, nm = 'Juu Duzu The Whirlwind' },
        ['yagudo piper'] = { pop = 15, nm = 'Vuu Puqu The Beguiler' },
    },
    ['grauberg [s]'] = {
        ['ajattara'] = { pop = 10, nm = 'Scitalis' },
        ['grauberg hippogryph'] = { pop = 5, nm = 'Kotan Kor Kamuy' },
        ['kotan kor kamuy'] = { cd = 10800, pop = 5 },
        ['scitalis'] = { cd = 3600, pop = 10 },
        ['vasiliceratops'] = { cd = 5400, pop = 10 },
        ['wivre'] = { pop = 10, nm = 'Vasiliceratops' },
    },
    ['gustav tunnel'] = {
        ['amikiri'] = { cd = 25200, pop = 5 },
        ['antares'] = { pop = 5, nm = 'Amikiri' },
        ['baobhan sith'] = { cd = 14400, pop = 5 },
        ['doom warlock'] = { pop = 5, nm = 'Taxim' },
        ['erlik'] = { pop = 5, nm = 'Baobhan Sith' },
        ['goblin mercenary'] = { pop = 10, nm = 'Wyvernpoacher Drachlox' },
        ['goblin reaper'] = { pop = 5, nm = 'Goblinsavior Heronox' },
        ['goblinsavior heronox'] = { cd = 10800, pop = 5 },
        ['taxim'] = { cd = 7200, pop = 5 },
        ['typhoon wyvern'] = { pop = 5, nm = 'Ungur' },
        ['ungur'] = { cd = 7200, pop = 5 },
        ['wyvernpoacher drachlox'] = { cd = 7200, pop = 10 },
    },
    ['ifrits cauldron'] = {
        ['eotyrannus'] = { pop = 5, nm = 'Lindwurm' },
        ['foreseer oramix'] = { cd = 3600, pop = 5 },
        ['goblin alchemist'] = { pop = 5, nm = 'Foreseer Oramix' },
        ['hurricane wyvern'] = { pop = 5, nm = 'Vouivre' },
        ['lindwurm'] = { cd = 3600, pop = 5 },
        ['sulfur scorpion'] = { pop = 5, nm = 'Tyrannic Tunnok' },
        ['tyrannic tunnok'] = { cd = 3600, pop = 5 },
        ['vouivre'] = { cd = 7200, pop = 5 },
    },
    ['inner horutoto ruins'] = {
        ['boggart'] = { pop = 10, nm = 'Nocuous Weapon' },
        ['goblin leecher'] = { pop = 10, nm = 'Slendlix Spindlethumb' },
        ['nocuous weapon'] = { cd = 1, pop = 10 },
        ['slendlix spindlethumb'] = { cd = 3600, pop = 10 },
    },
    ['jugner forest'] = {
        ['fradubio'] = { cd = 75600, pop = 10 },
        ['fraelissa'] = { pop = 10, nm = 'Fradubio' },
        ['orcish grunt'] = { pop = 10, nm = 'Supplespine Mujwuj' },
        ['supplespine mujwuj'] = { cd = 3600, pop = 10 },
    },
    ['jugner forest [s]'] = {
        ['decrepit gnole'] = { pop = 10, nm = 'Voirloup' },
        ['drumskull zogdregg'] = { cd = 3600, pop = 10 },
        ['orcish veteran'] = { pop = 10, nm = 'Drumskull Zogdregg' },
        ['voirloup'] = { cd = 60, pop = 10 },
    },
    ['king ranperres tomb'] = {
        ['crypt ghost'] = { cd = 3600, pop = 5 },
        ['gwyllgi'] = { cd = 3600, pop = 10 },
        ['nachzehrer'] = { pop = 10, nm = 'Gwyllgi' },
        ['tomb bat'] = { pop = 5, nm = 'Crypt Ghost' },
    },
    ['konschtat highlands'] = {
        ['rampaging ram'] = { cd = 1200, pop = 10 },
        ['steelfleece'] = { cd = 75600, pop = 10 },
        ['tremor ram'] = { pop = 10, nm = 'Rampaging Ram' },
    },
    ['korroloka tunnel'] = {
        ['bogy'] = { pop = 5, nm = 'Dame Blanche' },
        ['cargo crab colin'] = { cd = 5400, pop = 5 },
        ['clipper'] = { pop = 5, nm = 'Cargo Crab Colin' },
        ['dame blanche'] = { cd = 7200, pop = 5 },
        ['falcatus aranei'] = { cd = 7200, pop = 5 },
        ['huge spider'] = { pop = 5, nm = 'Falcatus Aranei' },
    },
    ['kuftal tunnel'] = {
        ['amemet'] = { cd = 4500, pop = 20 },
        ['arachne'] = { cd = 3600, pop = 5 },
        ['bloodthirster madkix'] = { cd = 7200, pop = 5 },
        ['deinonychus'] = { pop = 5, nm = 'Yowie' },
        ['goblin mercenary'] = { pop = 5, nm = 'Bloodthirster Madkix' },
        ['greater cockatrice'] = { pop = 10, nm = 'Pelican' },
        ['pelican'] = { cd = 14400, pop = 10 },
        ['recluse spider'] = { pop = 5, nm = 'Arachne' },
        ['sabotender mariachi'] = { cd = 10800, pop = 5 },
        ['sabotender sediendo'] = { pop = 5, nm = 'Sabotender Mariachi' },
        ['sand lizard'] = { pop = 20, nm = 'Amemet' },
        ['yowie'] = { cd = 3600, pop = 5 },
    },
    ['la theine plateau'] = {
        ['battering ram'] = { pop = 10, nm = 'Lumbering Lambert' },
        ['bloodtear'] = { cd = 75600, pop = 10 },
        ['lumbering lambert'] = { pop = 10, nm = 'Bloodtear' },
        ['poison funguar'] = { pop = 5, nm = 'Tumbling Truffle' },
        ['tumbling truffle'] = { cd = 3600, pop = 5 },
    },
    ['la vaule [s]'] = {
        ['ashmaker gotblut'] = { cd = 3600, pop = 10 },
        ['hawkeyed dnatbat'] = { cd = 3600, pop = 10 },
        ['orcish augur'] = { pop = 10, nm = 'Ashmaker Gotblut' },
        ['orcish bowshooter'] = { pop = 10, nm = 'Hawkeyed Dnatbat' },
    },
    ['labyrinth of onzozo'] = {
        ['flying manta'] = { pop = 4, nm = 'Lord Of Onzozo' },
        ['hellion'] = { cd = 7200, pop = 10 },
        ['labyrinth manticore'] = { pop = 10, nm = 'Narasimha' },
        ['lord of onzozo'] = { cd = 57600, pop = 4 },
        ['narasimha'] = { cd = 21600, pop = 10 },
        ['ose'] = { cd = 3600, pop = 5 },
        ['tainted flesh'] = { pop = 10, nm = 'Hellion' },
        ['torama'] = { pop = 5, nm = 'Ose' },
    },
    ['lower delkfutts tower'] = {
        ['epialtes'] = { cd = 1, pop = 5 },
        ['giant gatekeeper'] = { pop = 5, nm = 'Epialtes' },
        ['giant sentry'] = { pop = 5, nm = 'Hippolytos' },
        ['hippolytos'] = { cd = 1, pop = 5 },
    },
    ['lufaise meadows'] = {
        ['gigantobugard'] = { pop = 10, nm = 'Megalobugard' },
        ['megalobugard'] = { cd = 3600, pop = 10 },
    },
    ['mamook'] = {
        ['firedance magmaal ja'] = { cd = 3600, pop = 5 },
        ['watch wyvern'] = { pop = 5, nm = 'Firedance Magmaal Ja' },
        ['ziz'] = { pop = 5, nm = 'Zizzy Zillah' },
        ['zizzy zillah'] = { cd = 3600, pop = 5 },
    },
    ['maze of shakhrami'] = {
        ['maze maker'] = { pop = 10, nm = 'Trembler Tabitha' },
        ['trembler tabitha'] = { cd = 3600, pop = 10 },
    },
    ['meriphataud mountains'] = {
        ['coeurl'] = { pop = 15, nm = 'Patripatan' },
        ['daggerclaw dracos'] = { cd = 3600, pop = 10 },
        ['naa zeku the unwaiting'] = { cd = 3600, pop = 10 },
        ['patripatan'] = { cd = 3600, pop = 15 },
        ['raptor'] = { pop = 10, nm = 'Daggerclaw Dracos' },
        ['yagudo persecutor'] = { pop = 10, nm = 'Naa Zeku The Unwaiting' },
    },
    ['meriphataud mountains [s]'] = {
        ['centipedal centruroides'] = { cd = 3600, pop = 10 },
        ['mountain scolopendrid'] = { pop = 10, nm = 'Centipedal Centruroides' },
    },
    ['misareaux coast'] = {
        ['diatryma'] = { pop = 10, nm = 'Okyupete' },
        ['okyupete'] = { cd = 3600, pop = 10 },
    },
    ['mount zhayolm'] = {
        ['ignamoth'] = { cd = 7200, pop = 10 },
        ['wamoura'] = { pop = 10, nm = 'Ignamoth' },
    },
    ['north gustaberg'] = {
        ['maighdean uaine'] = { cd = 900, pop = 5 },
        ['walking sapling'] = { pop = 5, nm = 'Maighdean Uaine' },
    },
    ['north gustaberg [s]'] = {
        ['ankabut'] = { cd = 3600, pop = 10 },
        ['coppercap'] = { pop = 10, nm = 'Gloomanita' },
        ['gloomanita'] = { cd = 3600, pop = 10 },
        ['huge spider'] = { pop = 10, nm = 'Ankabut' },
    },
    ['ordelles caves'] = {
        ['agar agar'] = { cd = 3600, pop = 5 },
        ['donggu'] = { cd = 1, pop = 10 },
        ['fly agaric'] = { pop = 10, nm = 'Donggu' },
        ['jelly'] = { pop = 5, nm = 'Agar Agar' },
    },
    ['outer horutoto ruins'] = {
        ['ah puch'] = { cd = 3600, pop = 20 },
        ['desmodont'] = { cd = 3600, pop = 10 },
        ['ghoul'] = { pop = 20, nm = 'Ah Puch' },
        ['stink bats'] = { pop = 10, nm = 'Desmodont' },
    },
    ['palborough mines'] = {
        ['behya hundredwall'] = { cd = 3600, pop = 10 },
        ['bu ghi howlblade'] = { cd = 3600, pop = 10 },
        ['copper beetle'] = { pop = 10, nm = 'Bu Ghi Howlblade' },
        ['copper quadav'] = { pop = 10, nm = 'Behya Hundredwall' },
        ['old quadav'] = { pop = 10, nm = 'Behya Hundredwall' },
        ['veteran quadav'] = { pop = 20, nm = 'Zi Ghi Boneeater' },
        ['zi ghi boneeater'] = { cd = 3600, pop = 20 },
    },
    ['pashhow marshlands'] = {
        ['bloodpool vorax'] = { cd = 600, pop = 10 },
        ['goobbue'] = { pop = 10, nm = 'Jolly Green' },
        ['jolly green'] = { cd = 1, pop = 10 },
        ['ni zho bladebender'] = { cd = 3600, pop = 10 },
        ['thread leech'] = { pop = 10, nm = 'Bloodpool Vorax' },
        ['veteran quadav'] = { pop = 10, nm = 'Ni Zho Bladebender' },
    },
    ['pashhow marshlands [s]'] = {
        ['lou carcolh'] = { pop = 10, nm = 'Nommo' },
        ['nommo'] = { cd = 3600, pop = 10 },
        ['sugaar'] = { cd = 3600, pop = 5 },
        ['virulent peiste'] = { pop = 5, nm = 'Sugaar' },
    },
    ['psoxja'] = {
        ['diremite'] = { pop = 5, nm = 'Gyre Carlin' },
        ['gyre carlin'] = { cd = 1800, pop = 5 },
    },
    ['qufim island'] = {
        ['dancing weapon'] = { pop = 5, nm = 'Trickster Kinetix' },
        ['giant ascetic'] = { pop = 10, nm = 'Slippery Sucker' },
        ['giant hunter'] = { pop = 10, nm = 'Slippery Sucker' },
        ['giant ranger'] = { pop = 10, nm = 'Slippery Sucker' },
        ['giant trapper'] = { pop = 10, nm = 'Slippery Sucker' },
        ['slippery sucker'] = { cd = 600, pop = 10 },
        ['trickster kinetix'] = { cd = 3600, pop = 5 },
    },
    ['quicksand caves'] = {
        ['antican aedilis'] = { pop = 10, nm = 'Antican Tribunus' },
        ['antican hastatus'] = { pop = 10, nm = 'Antican Magister' },
        ['antican magister'] = { cd = 3600, pop = 10 },
        ['antican princeps'] = { pop = 10, nm = 'Sagittarius X Xiii' },
        ['antican signifer'] = { pop = 10, nm = 'Centurio X I' },
        ['antican triarius'] = { pop = 10, nm = 'Triarius X Xv' },
        ['antican tribunus'] = { cd = 3600, pop = 10 },
        ['centurio x i'] = { cd = 9000, pop = 10 },
        ['diamond daig'] = { cd = 3600, pop = 20 },
        ['helm beetle'] = { pop = 20, nm = 'Diamond Daig' },
        ['nussknacker'] = { cd = 3600, pop = 20 },
        ['sabotender bailaor'] = { pop = 10, nm = 'Sabotender Bailarin' },
        ['sabotender bailarin'] = { cd = 9000, pop = 10 },
        ['sabotender bailarina'] = { cd = 9000, pop = 10 },
        ['sagittarius x xiii'] = { cd = 14400, pop = 10 },
        ['sand lizard'] = { pop = 20, nm = 'Nussknacker' },
        ['spelunking sabotender'] = { pop = 10, nm = 'Sabotender Bailarina' },
        ['triarius x xv'] = { cd = 7200, pop = 10 },
    },
    ['ranguemont pass'] = {
        ['gloom eye'] = { cd = 3600, pop = 10 },
        ['hecteyes'] = { pop = 20, nm = 'Hyakume' },
        ['hyakume'] = { cd = 1, pop = 20 },
        ['seeker bats'] = { pop = 10, nm = 'Gloom Eye' },
    },
    ['riverne-site a01'] = {
        ['aiatar'] = { cd = 75600, pop = 10 },
        ['flamedrake'] = { pop = 10, nm = 'Aiatar' },
    },
    ['riverne-site b01'] = {
        ['imdugud'] = { cd = 75600, pop = 10 },
        ['nimbus hippogryph'] = { pop = 10, nm = 'Imdugud' },
    },
    ['rolanberry fields'] = {
        ['drooling daisy'] = { cd = 3600, pop = 10 },
        ['eldritch edge'] = { cd = 5400, pop = 10 },
        ['evil weapon'] = { pop = 10, nm = 'Eldritch Edge' },
        ['ochu'] = { pop = 10, nm = 'Drooling Daisy' },
    },
    ['rolanberry fields [s]'] = {
        ['death jacket'] = { pop = 10, nm = 'Erle' },
        ['delicieuse delphine ph'] = { cd = 5400, pop = 10 },
        ['dyinyinga'] = { cd = 3600, pop = 10 },
        ['erle'] = { cd = 5400, pop = 10 },
        ['ochu'] = { pop = 10, nm = 'Delicieuse Delphine Ph' },
        ['scabrous slug'] = { pop = 10, nm = 'Dyinyinga' },
    },
    ['romaeve'] = {
        ['magic flagon'] = { pop = 10, nm = 'Rogue Receptacle' },
        ['rogue receptacle'] = { cd = 7200, pop = 10 },
    },
    ['ruaun gardens'] = {
        ['despot'] = { cd = 7200, pop = 5 },
        ['groundskeeper'] = { pop = 5, nm = 'Despot' },
    },
    ['sauromugue champaign'] = {
        ['bashe'] = { cd = 3600, pop = 10 },
        ['deadly dodo'] = { cd = 3600, pop = 33 },
        ['hill lizard'] = { pop = 10, nm = 'Bashe' },
        ['tabar beak'] = { pop = 33, nm = 'Deadly Dodo' },
    },
    ['sauromugue champaign [s]'] = {
        ['balam quitz'] = { cd = 3600, pop = 10 },
        ['lynx'] = { pop = 10, nm = 'Balam Quitz' },
    },
    ['sea serpent grotto'] = {
        ['bog sahagin'] = { pop = 10, nm = 'Mouu The Waverider' },
        ['brook sahagin'] = { pop = 10, nm = 'Qull The Shellbuster' },
        ['charybdis'] = { cd = 28800, pop = 10 },
        ['coastal sahagin'] = { pop = 10, nm = 'Denn The Orcavoiced' },
        ['delta sahagin'] = { pop = 10, nm = 'Zuug The Shoreleaper' },
        ['denn the orcavoiced'] = { cd = 7200, pop = 10 },
        ['devil manta'] = { pop = 10, nm = 'Charybdis' },
        ['ghast'] = { pop = 10, nm = 'Namtar' },
        ['lagoon sahagin'] = { pop = 10, nm = 'Yarr The Pearleyed' },
        ['marsh sahagin'] = { pop = 10, nm = 'Worr The Clawfisted' },
        ['masan'] = { cd = 14400, pop = 10 },
        ['mouu the waverider'] = { cd = 7200, pop = 10 },
        ['namtar'] = { cd = 3600, pop = 10 },
        ['pahh the gullcaller'] = { cd = 7200, pop = 10 },
        ['qull the shellbuster'] = { cd = 7200, pop = 10 },
        ['razorjaw pugil'] = { pop = 10, nm = 'Sea Hog' },
        ['riparian sahagin'] = { pop = 10, nm = 'Seww The Squidlimbed' },
        ['royal leech'] = { pop = 10, nm = 'Masan' },
        ['sea hog'] = { cd = 3600, pop = 10 },
        ['seww the squidlimbed'] = { cd = 7200, pop = 10 },
        ['spring sahagin'] = { pop = 10, nm = 'Wuur The Sandcomber' },
        ['swamp sahagin'] = { pop = 10, nm = 'Pahh The Gullcaller' },
        ['worr the clawfisted'] = { cd = 7200, pop = 10 },
        ['wuur the sandcomber'] = { cd = 7200, pop = 10 },
        ['yarr the pearleyed'] = { cd = 3600, pop = 10 },
        ['zuug the shoreleaper'] = { cd = 7200, pop = 10 },
    },
    ['ship bound for mhaura'] = {
        ['sea horror'] = { cd = 1, pop = 20 },
        ['sea monk'] = { pop = 20, nm = 'Sea Horror' },
    },
    ['ship bound for selbina'] = {
        ['sea horror'] = { cd = 1, pop = 20 },
        ['sea monk'] = { pop = 20, nm = 'Sea Horror' },
    },
    ['south gustaberg'] = {
        ['carnero'] = { cd = 1, pop = 10 },
        ['ornery sheep'] = { pop = 10, nm = 'Carnero' },
    },
    ['tahrongi canyon'] = {
        ['canyon crawler'] = { pop = 10, nm = 'Herbage Hunter' },
        ['herbage hunter'] = { cd = 3600, pop = 10 },
    },
    ['temple of uggalepih'] = {
        ['flauros'] = { cd = 3600, pop = 10 },
        ['sozu sarberry'] = { cd = 3600, pop = 10 },
        ['sozu terberry'] = { cd = 3600, pop = 10 },
        ['tonberry cutter'] = { pop = 10, nm = 'Sozu Sarberry' },
        ['tonberry dismayer'] = { pop = 10, nm = 'Tonberry Kinq' },
        ['tonberry harrier'] = { pop = 10, nm = 'Sozu Terberry' },
        ['tonberry kinq'] = { cd = 21600, pop = 10 },
        ['torama'] = { pop = 10, nm = 'Flauros' },
    },
    ['the boyahda tree'] = {
        ['aquarius'] = { cd = 60, pop = 20 },
        ['boyahda sapling'] = { pop = 15, nm = 'Leshonki' },
        ['death cap'] = { pop = 10, nm = 'Ellyllon' },
        ['demonic rose'] = { pop = 10, nm = 'Voluptuous Vivian' },
        ['ellyllon'] = { cd = 7200, pop = 10 },
        ['leshonki'] = { cd = 3600, pop = 15 },
        ['moss eater'] = { pop = 5, nm = 'Unut' },
        ['robber crab'] = { pop = 20, nm = 'Aquarius' },
        ['unut'] = { cd = 7200, pop = 5 },
        ['voluptuous vivian'] = { cd = 57600, pop = 10 },
    },
    ['the eldieme necropolis'] = {
        ['cwn cyrff'] = { cd = 3600, pop = 15 },
        ['tomb wolf'] = { pop = 15, nm = 'Cwn Cyrff' },
    },
    ['the sanctuary of zitah'] = {
        ['goobbue gardener'] = { pop = 10, nm = 'Keeper Of Halidom' },
        ['keeper of halidom'] = { cd = 7200, pop = 10 },
    },
    ['toraimarai canal'] = {
        ['bouncing ball'] = { pop = 10, nm = 'Canal Moocher' },
        ['canal moocher'] = { cd = 3600, pop = 10 },
        ['konjac'] = { cd = 3600, pop = 10 },
        ['mousse'] = { pop = 10, nm = 'Konjac' },
    },
    ['uleguerand range'] = {
        ['bonnacon'] = { cd = 3600, pop = 5 },
        ['buffalo'] = { pop = 5, nm = 'Bonnacon' },
        ['magnotaur'] = { cd = 3600, pop = 10 },
        ['molech'] = { pop = 10, nm = 'Magnotaur' },
        ['polar hare'] = { pop = 10, nm = 'Skvader' },
        ['skvader'] = { cd = 3600, pop = 10 },
    },
    ['valkurm dunes'] = {
        ['damselfly'] = { pop = 10, nm = 'Valkurm Emperor' },
        ['giant bat'] = { pop = 5, nm = 'Golden Bat' },
        ['golden bat'] = { cd = 3600, pop = 5 },
        ['valkurm emperor'] = { cd = 1, pop = 10 },
    },
    ['vunkerl inlet [s]'] = {
        ['big bang'] = { cd = 3600, pop = 10 },
        ['ignis djinn'] = { pop = 10, nm = 'Big Bang' },
    },
    ['wajaom woodlands'] = {
        ['great ameretat'] = { pop = 10, nm = 'Jaded Jody' },
        ['jaded jody'] = { cd = 7200, pop = 10 },
        ['lesser colibri'] = { pop = 15, nm = 'Zoraal Jas Pkuucha' },
        ['zoraal jas pkuucha'] = { cd = 1800, pop = 15 },
    },
    ['west ronfaure'] = {
        ['forest hare'] = { pop = 9, nm = 'Jaggedy Eared Jack' },
        ['fungus beetle'] = { cd = 900, pop = 15 },
        ['jaggedy eared jack'] = { cd = 2400, pop = 9 },
        ['scarab beetle'] = { pop = 15, nm = 'Fungus Beetle' },
    },
    ['west sarutabaruta'] = {
        ['carrion crow'] = { pop = 10, nm = 'Nunyenunc' },
        ['nunyenunc'] = { cd = 3600, pop = 10 },
    },
    ['west sarutabaruta [s]'] = {
        ['jeduah'] = { cd = 3600, pop = 10 },
        ['ramponneau'] = { cd = 5400, pop = 20 },
        ['tiny lycopodium'] = { pop = 10, nm = 'Jeduah' },
        ['toad'] = { pop = 20, nm = 'Ramponneau' },
    },
    ['western altepa desert'] = {
        ['cactuar'] = { pop = 15, nm = 'Cactuar Cantautor' },
        ['cactuar cantautor'] = { cd = 3600, pop = 15 },
        ['calchas'] = { cd = 3600, pop = 10 },
        ['celphie'] = { cd = 7200, pop = 10 },
        ['desert dhalmel'] = { pop = 10, nm = 'Celphie' },
        ['phorusrhacos'] = { pop = 10, nm = 'Picolaton' },
        ['picolaton'] = { cd = 6400, pop = 10 },
        ['tulwar scorpion'] = { pop = 10, nm = 'Calchas' },
    },
    ['xarcabard'] = {
        ['barbaric weapon'] = { cd = 7200, pop = 10 },
        ['cursed weapon'] = { pop = 10, nm = 'Barbaric Weapon' },
        ['evil eye'] = { pop = 5, nm = 'Shadow Eye' },
        ['lost soul'] = { pop = 5, nm = 'Timeworn Warrior' },
        ['shadow eye'] = { cd = 3600, pop = 5 },
        ['timeworn warrior'] = { cd = 5400, pop = 5 },
    },
    ['xarcabard [s]'] = {
        ['dire gargouille'] = { pop = 10, nm = 'Graoully' },
        ['graoully'] = { cd = 3600, pop = 10 },
    },
    ['yhoator jungle'] = {
        ['hoar knuckled rimberry'] = { cd = 5400, pop = 10 },
        ['tonberry creeper'] = { pop = 10, nm = 'Hoar Knuckled Rimberry' },
        ['tonberry shadower'] = { pop = 10, nm = 'Hoar Knuckled Rimberry' },
    },
    ['yughott grotto'] = {
        ['ashmaker gotblut'] = { cd = 3600, pop = 5 },
        ['orcish grunt'] = { pop = 5, nm = 'Ashmaker Gotblut' },
        ['orcish stonechucker'] = { pop = 5, nm = 'Ashmaker Gotblut' },
    },
    ['yuhtunga jungle'] = {
        ['mischievous micholas'] = { cd = 3600, pop = 20 },
        ['young opo-opo'] = { pop = 20, nm = 'Mischievous Micholas' },
    },
};

--[[
* Current zone name, lowercased. Empty string if it cannot be resolved (during
* a zone transition the party record is briefly unusable).
--]]
function M.Zone()
    local ok, name = pcall(function()
        local id = AshitaCore:GetMemoryManager():GetParty():GetMemberZone(0);
        local s = AshitaCore:GetResourceManager():GetString('zones.names', id);
        if (type(s) ~= 'string') then return ''; end
        return s:gsub('%z', ''):lower();
    end);
    if (not ok) or (name == nil) then return ''; end
    return name;
end

--[[
* Look up a mob in the CURRENT zone. Returns the entry table or nil.
*
* Zone-scoped on purpose: mob names repeat across the world and the intervals
* do not. A bare name lookup would happily hand South Gustaberg's numbers to a
* same-named mob three zones away.
--]]
function M.Find(mobName)
    if (mobName == nil) or (mobName == '') then return nil; end
    local z = M.zones[M.Zone()];
    if (z == nil) then return nil; end
    return z[mobName:lower()];
end

function M.PH(mobName)
    local e = M.Find(mobName);
    return (e ~= nil) and e.ph or nil;
end

function M.CD(mobName)
    local e = M.Find(mobName);
    return (e ~= nil) and e.cd or nil;
end

-- Roster scraped from horizonffxi.wiki/Notorious_Monsters:_Level_Guide
-- (398 entries). Name -> zone. This is an IDENTITY table, not a timer
-- table: the wiki index carries no spawn/placeholder/cooldown columns.
-- Its job is to answer "is this actually an NM" so auto-register
-- cannot invent one from a mis-parsed chat line.
M.roster = {
    ['absolute virtue'] = 'Al\'Taieu',
    ['adamantoise'] = 'Valley of Sorrows',
    ['ahtu'] = 'Batallia Downs',
    ['aiatar'] = 'Riverne - Site A01',
    ['aipaloovik'] = 'Phanauet Channel',
    ['alastor antlion'] = 'Attohwa Chasm',
    ['alkyoneus'] = 'Upper Delkfutt\'s Tower',
    ['ambusher antlion'] = 'Attohwa Chasm',
    ['amemet'] = 'Kuftal Tunnel',
    ['amikiri'] = 'Gustav Tunnel',
    ['ancient goobbue'] = 'Boyahda Tree',
    ['antican consul'] = 'Quicksand Caves',
    ['antican legatus'] = 'Quicksand Caves',
    ['antican magister'] = 'Quicksand Caves',
    ['antican praefectus'] = 'Quicksand Caves',
    ['antican proconsul'] = 'Quicksand Caves',
    ['antican tribunus'] = 'Quicksand Caves',
    ['aquarius'] = 'Boyahda Tree',
    ['arachne'] = 'Kuftal Tunnel',
    ['argus'] = 'Maze of Shakhrami',
    ['arioch'] = 'Bostaunieux Oubliette',
    ['aroma crawler'] = 'Maze of Shakhrami',
    ['aroma fly'] = 'Gusgen Mines',
    ['aroma leech'] = 'Ordelle\'s Caves',
    ['ash dragon'] = 'Ifrit\'s Cauldron',
    ['ashmaker gotblut'] = 'Yughott Grotto',
    ['asphyxiated amsel'] = 'Gusgen Mines',
    ['aspidochelone'] = 'Valley of Sorrows',
    ['awd goggie'] = 'Crawlers\' Nest',
    ['balor'] = 'Sacrarium',
    ['baobhan sith'] = 'Gustav Tunnel',
    ['baron vapula'] = 'Castle Zvahl Keep',
    ['baronet romwe'] = 'Castle Zvahl Keep',
    ['bat eye'] = 'Ranguemont Pass',
    ['behemoth'] = 'Behemoth\'s Dominion',
    ['bendigeit vran'] = 'Konschtat Highlands',
    ['beryl-footed molberry'] = 'Temple of Uggalepih',
    ['bi\'gho headtaker'] = 'Beadeaux',
    ['biast'] = 'Xarcabard',
    ['big bomb'] = 'Halvung',
    ['bigmouth billy'] = 'East Ronfaure',
    ['bisque-heeled sunberry'] = 'Yhoator Jungle',
    ['bistre-hearted malberry'] = 'Den of Rancor',
    ['black coney'] = 'Uleguerand Range',
    ['black triple stars'] = 'Rolanberry Fields',
    ['blackbeard'] = 'Ferry - Mhaura/Selbina',
    ['bloodpool vorax'] = 'Pashhow Marshlands',
    ['bloodsucker'] = 'Bostaunieux Oubliette',
    ['bloodtear baldurf'] = 'La Theine Plateau',
    ['bloodthirster madkix'] = 'Kuftal Tunnel',
    ['bloody bones'] = 'Arrapago Reef',
    ['bloody vrukwuk'] = 'Ghelsba Outpost',
    ['blubbery bulge'] = 'Davoi',
    ['bluestreak gyugyuroon'] = 'Aydeewa Subterrane',
    ['bo\'who warmonger'] = 'Pashhow Marshlands',
    ['bomb king'] = 'Outer Horutoto Ruins',
    ['bomb queen'] = 'Ifrit\'s Cauldron',
    ['bonnacon'] = 'Uleguerand Range',
    ['boroka'] = 'Riverne - Site B01',
    ['brigandish blade'] = 'Ve\'Lugannon Palace',
    ['bright-handed kunberry'] = 'Yhoator Jungle',
    ['bu\'ghi howlblade'] = 'Palborough Mines',
    ['bubbly bernie'] = 'South Gustaberg',
    ['buburimboo'] = 'Buburimu Peninsula',
    ['bugbear matman'] = 'Newton Movalpolos',
    ['bugbear strongman'] = 'Oldton Movalpolos',
    ['bune'] = 'Gustav Tunnel',
    ['burned bergmann'] = 'Gusgen Mines',
    ['byakko'] = 'Ru\'Aun Gardens',
    ['cactrot rapido'] = 'Eastern Altepa Desert',
    ['cactuar cantautor'] = 'Western Altepa Desert',
    ['caithleann'] = 'Sacrarium',
    ['cancer'] = 'Kuftal Tunnel',
    ['capricious cassie'] = 'Fei\'Yin',
    ['cargo crab colin'] = 'Korroloka Tunnel',
    ['carmine dobsonfly'] = 'Riverne - Site A01',
    ['carmine-tailed janberry'] = 'Den of Rancor',
    ['carnero'] = 'South Gustaberg',
    ['celeste-eyed tozberry'] = 'Den of Rancor',
    ['celphie'] = 'Western Altepa Desert',
    ['cemetery cherry'] = 'King Ranperre\'s Tomb',
    ['centurio x-i'] = 'Quicksand Caves',
    ['centurio xii-i'] = 'Eastern Altepa Desert',
    ['cerberus'] = 'Mount Zhayolm',
    ['chariotbuster byakzak'] = 'Fort Ghelsba',
    ['charybdis'] = 'Sea Serpent Grotto',
    ['chocoboleech'] = 'Dangruf Wadi',
    ['citipati'] = 'Attohwa Chasm',
    ['colorful leshy'] = 'Lufaise Meadows',
    ['coo keja the unseen'] = 'Meriphataud Mountains',
    ['count bifrons'] = 'Castle Zvahl Keep',
    ['crimson-toothed pawberry'] = 'Temple of Uggalepih',
    ['crushed krause'] = 'Gusgen Mines',
    ['crypt ghost'] = 'King Ranperre\'s Tomb',
    ['crystal eater'] = 'Aydeewa Subterrane',
    ['cwn cyrff'] = 'Eldieme Necropolis',
    ['da\'dha hundredmask'] = 'Beadeaux',
    ['daggerclaw dracos'] = 'Meriphataud Mountains',
    ['dame blanche'] = 'Korroloka Tunnel',
    ['darting kachaal ja'] = 'Mamook',
    ['de\'vyu headhunter'] = 'Beadeaux',
    ['deadly dodo'] = 'Sauromugue Champaign',
    ['death from above'] = 'Temple of Uggalepih',
    ['defoliate leshy'] = 'Lufaise Meadows',
    ['demonic tiphia'] = 'Crawlers\' Nest',
    ['despot'] = 'Ru\'Aun Gardens',
    ['devout radol ja'] = 'Mamook',
    ['diamond daig'] = 'Quicksand Caves',
    ['diamond quadav'] = 'Qulun Dome',
    ['dirtyhanded gochakzuk'] = 'Davoi',
    ['doppelganger dio'] = 'Outer Horutoto Ruins',
    ['doppelganger gog'] = 'Outer Horutoto Ruins',
    ['dorgerwor the astute'] = 'Halvung',
    ['dosetsu tree'] = 'Qufim Island',
    ['dragonscaled bugaal ja'] = 'Mamook',
    ['drexerion the condemned'] = 'Bostaunieux Oubliette',
    ['drone crawler'] = 'Crawlers\' Nest',
    ['drooling daisy'] = 'Rolanberry Fields',
    ['duke haborym'] = 'Castle Zvahl Baileys',
    ['dune widow'] = 'Eastern Altepa Desert',
    ['eastern shadow'] = 'Fei\'Yin',
    ['eba'] = 'Phomiuna Aqueducts',
    ['edacious opo-opo'] = 'Yhoator Jungle',
    ['ellyllon'] = 'Boyahda Tree',
    ['emergent elm'] = 'Bhaflau Thickets',
    ['energetic eruca'] = 'Mount Zhayolm',
    ['enkelados'] = 'Upper Delkfutt\'s Tower',
    ['epialtes'] = 'Lower Delkfutt\'s Tower',
    ['ereshkigal'] = 'Xarcabard',
    ['eurymedon'] = 'Lower Delkfutt\'s Tower',
    ['eurytos'] = 'Middle Delkfutt\'s Tower',
    ['eyy mon the ironbreaker'] = 'Giddeus',
    ['fafnir'] = 'Dragon\'s Aery',
    ['falcatus aranei'] = 'Korroloka Tunnel',
    ['farlarder the shrewd'] = 'Halvung',
    ['father frost'] = 'Uleguerand Range',
    ['faust'] = 'Shrine of Ru\'Avitau',
    ['flauros'] = 'Temple of Uggalepih',
    ['fogweaver mozzfuzz'] = 'Ghelsba Outpost',
    ['foreseer oramix'] = 'Ifrit\'s Cauldron',
    ['foul meat'] = 'Gusgen Mines',
    ['fradubio'] = 'Jugner Forest',
    ['fraelissa'] = 'Jugner Forest',
    ['friar rush'] = 'Den of Rancor',
    ['frostmane'] = 'Cape Teriggan',
    ['fungus beetle'] = 'West Ronfaure',
    ['fyuu the seabellow'] = 'Sea Serpent Grotto',
    ['ga\'bhu unvanquished'] = 'Beadeaux',
    ['garfurlar the rabid'] = 'Mount Zhayolm',
    ['gargantua'] = 'Beaucedine Glacier',
    ['garharlor the unruly'] = 'Mount Zhayolm',
    ['garhorlur the brutal'] = 'Mount Zhayolm',
    ['ge\'dha evileye'] = 'Beadeaux',
    ['genbu'] = 'Ru\'Aun Gardens',
    ['geyser lizard'] = 'Dangruf Wadi',
    ['go\'bhu gascon'] = 'Beadeaux',
    ['goblin archaeologist'] = 'La Theine Plateau',
    ['goblin collector'] = 'Newton Movalpolos',
    ['goblin wolfman'] = 'Oldton Movalpolos',
    ['goblinsavior heronox'] = 'Gustav Tunnel',
    ['golden bat'] = 'Valkurm Dunes',
    ['golden-tongued culberry'] = 'Pso\'Xja',
    ['goliath'] = 'Fei\'Yin',
    ['grand duke batym'] = 'Castle Zvahl Baileys',
    ['gration'] = 'Misareaux Coast',
    ['guardian crawler'] = 'Crawlers\' Nest',
    ['guivre'] = 'Kuftal Tunnel',
    ['gulool ja ja'] = 'Mamook',
    ['gurfurlur the menacing'] = 'Halvung',
    ['habetrot'] = 'Temple of Uggalepih',
    ['hakutaku'] = 'Den of Rancor',
    ['hastatus xi-xii'] = 'Quicksand Caves',
    ['haty'] = 'Konschtat Highlands',
    ['hawkeyed dnatbat'] = 'Davoi',
    ['heliodromos'] = 'Riverne - Site A01',
    ['helldiver'] = 'Buburimu Peninsula',
    ['hellion'] = 'Labyrinth of Onzozo',
    ['hercules beetle'] = 'Carpenters\' Landing',
    ['hippolytos'] = 'Lower Delkfutt\'s Tower',
    ['hoo mjuu the torrent'] = 'Giddeus',
    ['hundredfaced hapool ja'] = 'Mamook',
    ['hundredscar hajwaj'] = 'Fort Ghelsba',
    ['hydra'] = 'Wajaom Woodlands',
    ['imdugud'] = 'Riverne - Site B01',
    ['indich'] = 'Sacrarium',
    ['intulo'] = 'Bibiki Bay',
    ['ix\'aern (mnk)'] = 'Grand Palace of Hu\'Xzoi',
    ['ixtab'] = 'Upper Delkfutt\'s Tower',
    ['jaded jody'] = 'Wajaom Woodlands',
    ['jaggedy-eared jack'] = 'West Ronfaure',
    ['jailer of faith'] = 'The Garden of Ru\'Hmet',
    ['jailer of fortitude'] = 'The Garden of Ru\'Hmet',
    ['jailer of hope'] = 'Al\'Taieu',
    ['jailer of justice'] = 'Al\'Taieu',
    ['jailer of love'] = 'Al\'Taieu',
    ['jailer of prudence'] = 'Al\'Taieu',
    ['jailer of temperance'] = 'Grand Palace of Hu\'Xzoi',
    ['jolly green'] = 'Pashhow Marshlands',
    ['jormungand'] = 'Uleguerand Range',
    ['juggler hecatomb'] = 'Gusgen Mines',
    ['juu duzu the whirlwind'] = 'Giddeus',
    ['keeper of halidom'] = 'Sanctuary of Zi\'Tah',
    ['king arthro'] = 'Jugner Forest',
    ['king behemoth'] = 'Behemoth\'s Dominion',
    ['king vinegarroon'] = 'Western Altepa Desert',
    ['kirata'] = 'Beaucedine Glacier',
    ['kirin'] = 'Shrine of Ru\'Avitau',
    ['kirlirger the abhorrent'] = 'Halvung',
    ['kreutzet'] = 'Cape Teriggan',
    ['kurrea'] = 'Lufaise Meadows',
    ['leaping lizzy'] = 'South Gustaberg',
    ['leech king'] = 'Maze of Shakhrami',
    ['leshonki'] = 'Boyahda Tree',
    ['lich c magnus'] = 'Eldieme Necropolis',
    ['lindwurm'] = 'Ifrit\'s Cauldron',
    ['lobais'] = 'Sacrarium',
    ['lord of onzozo'] = 'Labyrinth of Onzozo',
    ['luaith'] = 'Sacrarium',
    ['lumber jack'] = 'Batallia Downs',
    ['lumbering lambert'] = 'La Theine Plateau',
    ['mahisha'] = 'Phomiuna Aqueducts',
    ['maighdean uaine'] = 'North Gustaberg',
    ['maltha'] = 'Inner Horutoto Ruins',
    ['manes'] = 'Bostaunieux Oubliette',
    ['marquis allocen'] = 'Castle Zvahl Baileys',
    ['marquis amon'] = 'Castle Zvahl Baileys',
    ['masan'] = 'Sea Serpent Grotto',
    ['matron crawler'] = 'Crawlers\' Nest',
    ['medusa'] = 'Arrapago Reef',
    ['mee deggi the punisher'] = 'Castle Oztroja',
    ['meteormauler zhagtegg'] = 'Jugner Forest',
    ['meww the turtlerider'] = 'Yuhtunga Jungle',
    ['mimas'] = 'Upper Delkfutt\'s Tower',
    ['mischievous micholas'] = 'Yuhtunga Jungle',
    ['moo ouzi the swiftblade'] = 'Castle Oztroja',
    ['morbolger'] = 'Ordelle\'s Caves',
    ['morion worm'] = 'Korroloka Tunnel',
    ['mother globe'] = 'Shrine of Ru\'Avitau',
    ['mountain worm'] = 'Uleguerand Range',
    ['mouu the waverider'] = 'Sea Serpent Grotto',
    ['mycophile'] = 'Carpenters\' Landing',
    ['mysticmaker profblix'] = 'Labyrinth of Onzozo',
    ['namtar'] = 'Sea Serpent Grotto',
    ['narasimha'] = 'Labyrinth of Onzozo',
    ['nidhogg'] = 'Dragon\'s Aery',
    ['nightmare vase'] = 'Ro\'Maeve',
    ['nihniknoovi'] = 'La Theine Plateau',
    ['no\'mho crimsonarmor'] = 'Palborough Mines',
    ['noble mold'] = 'Sanctuary of Zi\'Tah',
    ['northern shadow'] = 'Fei\'Yin',
    ['novv the whitehearted'] = 'Sea Serpent Grotto',
    ['nue'] = 'Beaucedine Glacier',
    ['nunyenunc'] = 'West Sarutabaruta',
    ['nussknacker'] = 'Quicksand Caves',
    ['ocean sahagin'] = 'Sea Serpent Grotto',
    ['odqan'] = 'Misareaux Coast',
    ['ogama'] = 'Den of Rancor',
    ['ogygos'] = 'Middle Delkfutt\'s Tower',
    ['old two-wings'] = 'Garlaige Citadel',
    ['olla grande'] = 'Shrine of Ru\'Avitau',
    ['oni carcass'] = 'Toraimarai Canal',
    ['ophion'] = 'Middle Delkfutt\'s Tower',
    ['orcish hexspinner'] = 'Monastic Cavern',
    ['orcish overlord'] = 'Monastic Cavern',
    ['orcish panzer'] = 'Fort Ghelsba',
    ['orcish wallbreacher'] = 'Ghelsba Outpost',
    ['orcish warlord'] = 'Monastic Cavern',
    ['orctrap'] = 'Carpenters\' Landing',
    ['ose'] = 'Labyrinth of Onzozo',
    ['overlord bakgodek'] = 'Monastic Cavern',
    ['padfoot'] = 'Lufaise Meadows',
    ['pahh the gullcaller'] = 'Sea Serpent Grotto',
    ['pallas'] = 'Upper Delkfutt\'s Tower',
    ['panzer percival'] = 'Jugner Forest',
    ['peallaidh'] = 'Caedarva Mire',
    ['peg powler'] = 'Labyrinth of Onzozo',
    ['pelican'] = 'Kuftal Tunnel',
    ['phanduron the condemned'] = 'Bostaunieux Oubliette',
    ['phantom worm'] = 'Kuftal Tunnel',
    ['poisonhand gnadgad'] = 'Davoi',
    ['polybotes'] = 'Middle Delkfutt\'s Tower',
    ['porphyrion'] = 'Upper Delkfutt\'s Tower',
    ['proconsul xii'] = 'Quicksand Caves',
    ['proteus'] = 'Ferry - Nashmau/Al Zahbi',
    ['pulverized pfeffer'] = 'Gusgen Mines',
    ['queen crawler'] = 'Crawlers\' Nest',
    ['qull the shellbuster'] = 'Sea Serpent Grotto',
    ['quu domi the gallant'] = 'Castle Oztroja',
    ['rampaging ram'] = 'Konschtat Highlands',
    ['ravin raven'] = 'Caedarva Mire',
    ['rhoikos'] = 'Middle Delkfutt\'s Tower',
    ['rhoitos'] = 'Middle Delkfutt\'s Tower',
    ['roc'] = 'Sauromugue Champaign',
    ['rose garden'] = 'Yuhtunga Jungle',
    ['sabotender bailarin'] = 'Quicksand Caves',
    ['sabotender bailarina'] = 'Quicksand Caves',
    ['sabotender mariachi'] = 'Kuftal Tunnel',
    ['sacrificial goblet'] = 'Temple of Uggalepih',
    ['sagittarius x-xiii'] = 'Quicksand Caves',
    ['sea hog'] = 'Sea Serpent Grotto',
    ['sea horror'] = 'Ship bound for Mhaura',
    ['seiryu'] = 'Ru\'Aun Gardens',
    ['serket'] = 'Garlaige Citadel',
    ['serpopard ishtar'] = 'Tahrongi Canyon',
    ['serra'] = 'Bibiki Bay - Purgonorgo Isle',
    ['sewer syrup'] = 'Bostaunieux Oubliette',
    ['seww the squidlimbed'] = 'Sea Serpent Grotto',
    ['shadow eye'] = 'Xarcabard',
    ['sharp-eared ropipi'] = 'East Sarutabaruta',
    ['shen'] = 'Bibiki Bay - Purgonorgo Isle',
    ['shieldtrap'] = 'Riverne - Site A01',
    ['shii'] = 'Bostaunieux Oubliette',
    ['shikigami weapon'] = 'Ro\'Maeve',
    ['silverhook'] = 'Ferry - Mhaura/Selbina',
    ['simurgh'] = 'Rolanberry Fields',
    ['skewer sam'] = 'Garlaige Citadel',
    ['skull of envy'] = 'Eldieme Necropolis',
    ['skull of gluttony'] = 'Eldieme Necropolis',
    ['skull of greed'] = 'Eldieme Necropolis',
    ['skull of lust'] = 'Eldieme Necropolis',
    ['skull of pride'] = 'Eldieme Necropolis',
    ['skull of sloth'] = 'Eldieme Necropolis',
    ['skull of wrath'] = 'Eldieme Necropolis',
    ['smothered schmidt'] = 'Gusgen Mines',
    ['snow maiden'] = 'Uleguerand Range',
    ['soulstealer skullnix'] = 'Labyrinth of Onzozo',
    ['southern shadow'] = 'Fei\'Yin',
    ['sozu bliberry'] = 'Den of Rancor',
    ['sozu rogberry'] = 'Temple of Uggalepih',
    ['sozu sarberry'] = 'Temple of Uggalepih',
    ['sozu terberry'] = 'Temple of Uggalepih',
    ['spiny spipi'] = 'East Sarutabaruta',
    ['steam cleaner'] = 'Ve\'Lugannon Palace',
    ['steelbiter gudrud'] = 'Davoi',
    ['steelfleece baldarich'] = 'Konschtat Highlands',
    ['stinging sophie'] = 'North Gustaberg',
    ['stray mary'] = 'Konschtat Highlands',
    ['stubborn dredvodd'] = 'Phanauet Channel',
    ['suzaku'] = 'Ru\'Aun Gardens',
    ['swamfisk'] = 'East Ronfaure',
    ['swashstox beadblinker'] = 'Newton Movalpolos',
    ['taisaijin'] = 'Ranguemont Pass',
    ['tarasque'] = 'Ifrit\'s Cauldron',
    ['tawny-fingered mugberry'] = 'Den of Rancor',
    ['taxim'] = 'Gustav Tunnel',
    ['thousandarm deshglesh'] = 'Ghelsba Outpost',
    ['tiamat'] = 'Attohwa Chasm',
    ['tigerbane bakdak'] = 'Davoi',
    ['tom tit tat'] = 'West Sarutabaruta',
    ['tonberry decapitator'] = 'Den of Rancor',
    ['tonberry kinq'] = 'Temple of Uggalepih',
    ['tonberry tracker'] = 'Den of Rancor',
    ['tottering toby'] = 'Batallia Downs',
    ['tres duendes'] = 'Phomiuna Aqueducts',
    ['triarius x-xv'] = 'Quicksand Caves',
    ['tribunus vii-i'] = 'Quicksand Caves',
    ['trickster kinetix'] = 'Qufim Island',
    ['tumbling truffle'] = 'La Theine Plateau',
    ['tyrannic tunnok'] = 'Ifrit\'s Cauldron',
    ['tzee xicu the manifest'] = 'Castle Oztroja',
    ['ullikummi'] = 'Shrine of Ru\'Avitau',
    ['ungur'] = 'Gustav Tunnel',
    ['unstable cluster'] = 'Riverne - Site B01',
    ['unut'] = 'Boyahda Tree',
    ['upyri'] = 'Misareaux Coast',
    ['valkurm emperor'] = 'Valkurm Dunes',
    ['viscount morax'] = 'Castle Zvahl Keep',
    ['vodyanoi'] = 'Phanauet Channel',
    ['voll the sharkfinned'] = 'Sea Serpent Grotto',
    ['voluptuous vivian'] = 'Boyahda Tree',
    ['vouivre'] = 'Ifrit\'s Cauldron',
    ['vrtra'] = 'King Ranperre\'s Tomb',
    ['vuu puqu the beguiler'] = 'Giddeus',
    ['waraxe beak'] = 'Meriphataud Mountains',
    ['weeping willow'] = 'Batallia Downs',
    ['western shadow'] = 'Fei\'Yin',
    ['white coney'] = 'Uleguerand Range',
    ['woodland sage'] = 'Yhoator Jungle',
    ['worr the clawfisted'] = 'Sea Serpent Grotto',
    ['wounded wurfel'] = 'Gusgen Mines',
    ['wuur the sandcomber'] = 'Sea Serpent Grotto',
    ['wyvernpoacher drachlox'] = 'Gustav Tunnel',
    ['xolotl'] = 'Attohwa Chasm',
    ['yaa haqa the profane'] = 'Castle Oztroja',
    ['yagudo avatar'] = 'Castle Oztroja',
    ['yara ma yha who'] = 'Tahrongi Canyon',
    ['yowie'] = 'Kuftal Tunnel',
    ['za\'dha adamantking'] = 'Qulun Dome',
    ['zhuu buxu the silent'] = 'Giddeus',
    ['zi\'ghi boneeater'] = 'Palborough Mines',
    ['zikko'] = 'Caedarva Mire',
    ['zipacna'] = 'Ve\'Lugannon Palace',
    ['ziphius'] = 'Misareaux Coast',
    ['zizzy zillah'] = 'Mamook',
    ['zo\'khu blackcloud'] = 'Beadeaux',
    ['zoraal ja\'s pkuucha'] = 'Wajaom Woodlands',
    ['zoredonite'] = 'Manaclipper',
    ['zuug the shoreleaper'] = 'Sea Serpent Grotto',
};

--[[
* Is this name a known notorious monster? Zone-independent on purpose: the
* roster is an identity check, and a mob's name is unique enough for that.
* Zone still gates the TIMER lookup in M.Find, where intervals differ.
--]]
function M.IsNM(name)
    if (name == nil) then return false; end
    return M.roster[name:lower():gsub('^the ', '')] ~= nil;
end

--[[
* Home zone for a known NM, or nil. Useful for sanity-checking a match: if
* you are in Castle Oztroja and something claims to be Leaping Lizzy, the
* chat line was mis-parsed.
--]]
function M.HomeZone(name)
    if (name == nil) then return nil; end
    return M.roster[name:lower():gsub('^the ', '')];
end


--[[
* Lottery chance per placeholder death, as a percentage, or nil. From LSB's
* phOnDespawn argument 3 - the wiki publishes this for almost nothing.
--]]
function M.PopChance(mobName)
    local e = M.Find(mobName);
    return (e ~= nil) and e.pop or nil;
end

--[[
* Which NM does this placeholder roll for? nil if it is not a placeholder in
* the current zone.
--]]
function M.PHFor(mobName)
    local e = M.Find(mobName);
    return (e ~= nil) and e.nm or nil;
end

return M;
